export const shadcnBreadcrumbListClassName = 'flex flex-wrap items-center gap-1.5 text-sm break-words sm:gap-2.5'
export const shadcnBreadcrumbLinkClassName = 'hover:text-foreground transition-colors'
export const shadcnBreadcrumbPageClassName = 'text-foreground font-normal'
export const shadcnBreadcrumbSeparatorClassName = '[&>svg]:size-3.5'
export const shadcnBreadcrumbEllipsisClassName = 'flex size-9 items-center justify-center'
